# Generated by Django 2.2.6 on 2019-10-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='sources',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
